---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: macos-1014-local
provisioner:
  name: ansible
verifier:
  name: testinfra
