---
- name: Check if toolchain is alredy installed at {{ toolchain_final_dest }}
  stat:
    path: "{{ toolchain_final_dest }}"
  register: final_dest

- name: Check version file if toolchain is installed
  stat:
    path: "{{ toolchain_final_dest }}/toolchain_version"
  register: version_file
  when:
    - final_dest.stat.exists

- name: Get toolchain version if installed
  command: cat {{ toolchain_final_dest }}/toolchain_version
  register: version_value
  changed_when: false
  when:
    - final_dest.stat.exists
    - version_file is defined
    - version_file.stat.exists | default(false)

- name: Delete old toolchain if specified
  become: true
  file:
    path: "{{ toolchain_final_dest }}"
    state: absent
  when:
    - toolchain_delete_old_final_dest
    - version_value.stdout | default("none") != toolchain_version

- name: Download toolchain from {{ toolchain_url }}
  get_url:
    url: "{{ toolchain_url }}"
    dest: "{{ toolchain_unpack_dest }}/{{ toolchain_url | basename }}"
    validate_certs: "{{ toolchain_validate_certs }}"
    mode: 0750
  when:
    - version_value.stdout | default("none") != toolchain_version

- name: Unpack toolchain from {{ toolchain_unpack_dest }}
  become: true
  unarchive:
    creates: "{{ toolchain_creates_directory | default(omit) }}"
    dest: "{{ toolchain_unpack_dest }}"
    list_files: "{{ toolchain_list_files }}"
    remote_src: true
    src: "{{ toolchain_unpack_dest }}/{{ toolchain_url | basename }}"
  register: toolchain_archive_contents
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
  when:
    - version_value.stdout | default("none") != toolchain_version

- name: Remove the downloaded file
  file:
    path: "{{ toolchain_unpack_dest }}/{{ toolchain_url | basename }}"
    state: "absent"

- name: Pass file contents
  set_fact:
    toolchain_top_level_directory: "{{ toolchain_archive_contents.files[0] }}"
  when:
    - toolchain_archive_contents.changed
    - toolchain_list_files
