---
- name: Check if toolchain is alredy installed
  stat:
    path: "{{ toolchain_final_dest }}"
  register: final_dest

- name: Check version file if toolchain is installed
  stat:
    path: "{{ toolchain_final_dest }}/toolchain_version"
  register: version_file
  when:
    - final_dest.stat.exists

- name: Get toolchain version if installed
  command: cat {{ toolchain_final_dest }}/toolchain_version
  register: version_value
  changed_when: false
  when:
    - version_file.stat.exists | default(false)

- name: Download toolchain from {{ toolchain_url }}
  become: true
  unarchive:
    creates: "{{ toolchain_creates_directory | default(omit) }}"
    dest: "{{ toolchain_unpack_dest }}"
    list_files: true
    remote_src: true
    src: "{{ toolchain_url }}"
  async: "{{ toolchain_async | default(omit) }}"
  poll: "{{ toolchain_poll | default(omit) }}"
  register: toolchain_archive_contents
  when:
    - version_value.stdout | default("none") != toolchain_version

- name: Pass file contents
  set_fact:
    toolchain_top_level_directory: "{{ toolchain_archive_contents.files[0] }}"
  when:
    - toolchain_archive_contents.changed
