---
- name: Download toolchain
  unarchive:
    dest: "{{ toolchain_dest }}"
    remote_src: true
    src: "{{ toolchain_url }}"
    list_files: "{{ toolchain_list_files }}"
  register: toolchain_archive_contents

- name: Pass file contents if list files is true
  set_fact:
    toolchain_top_level_directory: "{{ toolchain_archive_contents.files[0] }}"
  when: toolchain_list_files == true
