---
jobs:
  test:
    name: molecule test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install required dependencies
        run: pip install -r requirements.txt
      - name: Log into RedHat
        uses: azure/docker-login@v1
        with:
          login-server: registry.redhat.io
          username: &rhr_user ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME }}
          password: &rhr_pass ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD }}
      - run: molecule test
        env:
          REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME: *rhr_user
          REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD: *rhr_pass
      - run: molecule test -s delete_first
        env:
          REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME: *rhr_user
          REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD: *rhr_pass
name: Molecule Test
'on':
  - push
